name: DuckDB Workflow Trigger
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Trigger DuckDB workflows
      run: |
        curl -XPOST -u "${{secrets.PAT_USER}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/duckdb/duckdb/dispatches --data '{"event_type": "nightly-build"}'
